### ISSUE TITLE
Two classes out of there proper packages

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail** [OmneyaOsman/MovieAppliation#5]
Great effort, just there is a small comment,
The network-checker should be in the domain layer, not presentation layer (you use it in the domain layer, it cannot be present in the presentation)

And the transformer class that is in the features package, it is not a feature, it can be in the core package

Good job 👍🏼👍🏼

**Comment by OmneyaOsman** [comment]
Thanks a lot your comment means a lot to and really helped me to figure out where to put them , and I couldn't that level of coding without your great effort in the bootcamp

**Comment by Ahmed-Adel-Ismail** [comment]
I did nothing, it is all your efforts
