### ISSUE TITLE
Unnecessary coupling

### ISSUE THREAD

**Issue by fadi-botros** [OmneyaOsman/MovieAppliation#6]
At first, I could say: legendary work, keep it up 👍 🥇 

But there are some issues:
  1. Unnecessary coupling by zipping the 2 observation of lists in one observable
https://github.com/OmneyaOsman/Movie-Zone/blob/2b30a1bebadfc3882491faf9fc6e20c272e64e20/app/src/main/java/com/omni/movieappliation/features/home/MoviesHomeViewModel.kt#L40

Why not just get the 2 observables and observe on each one separately ?

(But anyway very good and careful way to avoid memory leaks by using Disposable and onCleared)

  2. The extensions file, why it is in a single separate file for all the activities? I think it should be each in its activity package (such as putting the `MainActivity.bindViews` in `com.omni.movieappliation.features.home` and `DetailsActivity.bindViews` in `com.omni.movieappliation.features.details`)

Also, since it is a common method, why not try to think to put it in an interface and think how can you remove some repetitions? (This could be just a cosmetic change because normally bindViews doesn't have really common code, but it is just a common method)

  3. In the entity classes, the names should be camel cased, not C-style variables (for example: try to use `posterPath` instead of `poster_path` and use any alternative way to map it from the API, like the GSON annotations)

  4. Also, there are empty unit tests, either remove the test packages or add unit tests.

  5. Please,   don't ruin all this very extra good work with wrong spacing, blank lines and typos. Please learn the correct style regarding spacing and leaving blank lines. And revise the typos (example of the typos is "Screenshoots", it is "Screenshots" without the extra "o", and the name of the application package itself, it is "movieapplication" not "movieappliation", there is a missing "c")

**Comment by OmneyaOsman** [comment]
thanks, a lot fadi for your great review I appreciated it and I will work on that tips
